kubeProxyReplacement: true 
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
encryption:
  enabled: true
  type: wireguard
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble-ui.127.0.0.1.nip.io
