kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
      - hostPath: /proc
        containerPath: /procHost
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    listenAddress: 127.0.0.1
    protocol: TCP
- role: worker
  extraMounts:
    - hostPath: /proc
      containerPath: /procHost
- role: worker
  extraMounts:
    - hostPath: /proc
      containerPath: /procHost
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
