version: '3'

tasks:
  up:
    cmds: 
      - helm repo add cilium https://helm.cilium.io/ --force-update
      - helm repo add headlamp https://kubernetes-sigs.github.io/headlamp/ --force-update
      - kind create cluster -n kind --config=cluster.yaml
      - helm upgrade --install cilium cilium/cilium --version 1.17.2 --namespace kube-system --values cilium-helm-values.yaml
      - helm upgrade --install headlamp headlamp/headlamp --namespace kube-system -f headlamp-helm-values.yaml

  down:
    cmds:
      - kind delete cluster -n kind
